version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - apiNetwork

  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - "3000:3000"
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - apiNetwork

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      -  apiNetwork

volumes:
  mongodb_data_container:

networks:
  apiNetwork:
    name: api-network
    driver: bridge